server {
	#3
	#
	listen 127.0.0.1:9090
	server_name server3;
	autoindex off
	
	upload_path /upload/
	root server3
	index indexGeek.html
	methods GET
	location /storage {
		methods GET POST DELETE
	}
	location /storage2 {
		methods GET POST DELETE
	}
	location /youtube {
		redirection www.youtube.com 302
	}
}


